package com.myspace.masterproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class intObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public intObject() {
    }




}