package com.myspace.masterproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class intObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigInteger myInt;

	public intObject() {
	}

	public java.math.BigInteger getMyInt() {
		return this.myInt;
	}

	public void setMyInt(java.math.BigInteger myInt) {
		this.myInt = myInt;
	}

	public intObject(java.math.BigInteger myInt) {
		this.myInt = myInt;
	}

}