package com.myspace.masterproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class release implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public release() {
    }




}